/* ==========================================================================
   EQ Sentry — production build.
   Copies the whole site into dist/ and minifies the CSS + JS there, leaving the
   source files readable. Deploy the dist/ folder.

     npm install      # one time (clean-css + terser)
     npm run build    # produces ./dist
     # then deploy ./dist  (it already contains _headers, manifest, data, etc.)

   Requires Node 18+. clean-css/terser are correct minifiers — they preserve
   calc() spacing, strings, and only mangle local variables (not window.EQ etc.),
   so this is safe in a way a hand-rolled regex minifier is not.

   Note: most hosts (Netlify, Cloudflare, Vercel) already gzip/brotli responses,
   which delivers ~70–75% of this size win automatically. This build adds the
   rest and is worth wiring into CI.
   ========================================================================== */
import { cp, mkdir, rm, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { execFileSync } from "node:child_process";
import CleanCSS from "clean-css";
import { minify as terser } from "terser";

const ROOT = process.cwd();
const DIST = path.join(ROOT, "dist");

// Explicit allowlist: local backups, logs, dotfiles, .env files, tooling and
// other untracked workspace content must never leak into a deployed bundle.
const SITE_DIRS = new Set(["assets", "data"]);
const SITE_FILES = new Set([
  "_headers", "_redirects", ".nojekyll", "CNAME",
  "manifest.webmanifest", "netlify.toml", "robots.txt", "service-worker.js", "sitemap.xml"
]);

function shouldShip(entry) {
  return entry.isDirectory()
    ? SITE_DIRS.has(entry.name)
    : entry.name.endsWith(".html") || SITE_FILES.has(entry.name);
}

async function walk(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...await walk(p));
    else out.push(p);
  }
  return out;
}

const kb = (n) => (n / 1024).toFixed(1) + " KB";

await rm(DIST, { recursive: true, force: true });
await mkdir(DIST, { recursive: true });

// fs.cp rejects copying a directory into one of its own descendants before its
// filter runs. Copy each shippable top-level entry instead so dist/ can live in
// the project root without recursively copying itself.
for (const entry of await readdir(ROOT, { withFileTypes: true })) {
  if (!shouldShip(entry)) continue;
  await cp(path.join(ROOT, entry.name), path.join(DIST, entry.name), {
    recursive: true
  });
}
await writeFile(path.join(DIST, ".eqsentry-static-root"), "generated by npm run build\n");

// Build-time config injection: override the CARTO basemap tile templates from the
// environment (Vercel → Settings → Environment Variables). This runs before the
// minify pass so terser sees the final values. Unset vars keep config.js's own
// defaults, so a plain `npm run build` still produces a working bundle — and the
// unbuilt repo root (what GitHub Pages serves) keeps working untouched.
const CONFIG_JS = path.join(DIST, "assets", "js", "config.js");
const basemapOverrides = [
  ["key", "CARTO_API_KEY", process.env.CARTO_API_KEY],
  ["dark", "CARTO_BASEMAP_DARK", process.env.CARTO_BASEMAP_DARK],
  ["light", "CARTO_BASEMAP_LIGHT", process.env.CARTO_BASEMAP_LIGHT]
].filter(([, , value]) => value && value.trim());
if (basemapOverrides.length) {
  let cfg = await readFile(CONFIG_JS, "utf8");
  for (const [prop, envName, value] of basemapOverrides) {
    const re = new RegExp(`(\\n\\s*${prop}:\\s*)"[^"]*"`);
    if (!re.test(cfg)) throw new Error(`config.js: no ${prop} literal to replace`);
    cfg = cfg.replace(re, `$1${JSON.stringify(value.trim())}`);
    // Never print the key itself — build logs are not a safe place for it.
    console.log(`Basemap ${prop} <- ${envName}${prop === "key" ? " (value hidden)" : ""}`);
  }
  await writeFile(CONFIG_JS, cfg);
}

/* ── Pre-render the English i18n strings into the markup ───────────────────
   Every page ships its copy inside <script id="page-i18n"> and its elements
   empty (<h1 data-i18n="pp.h1"></h1>), with i18n.js filling them in at runtime.
   That means a crawler with no JS sees a blank page — index.html had an empty
   <h1> and ~85 characters of body text. Google renders JS, but on a deferred
   pass, and pages with no static content routinely fail to get indexed.

   So bake the English strings into the markup here. The JSON block stays put,
   so i18n.js still works exactly as before and the Nepali switch is unaffected
   — it just overwrites identical English text on load instead of empty nodes.
   Only elements that are empty are touched; anything with content is left be. */
const escHTML = (s) => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function prerenderI18n(html) {
  const block = html.match(
    /<script[^>]*id="page-i18n"[^>]*>([\s\S]*?)<\/script>/i
  );
  if (!block) return { html, filled: 0 };
  let dict;
  try { dict = (JSON.parse(block[1]) || {}).en; } catch { return { html, filled: 0 }; }
  if (!dict) return { html, filled: 0 };

  let filled = 0;
  // Empty element carrying data-i18n / data-i18n-html -> insert the string.
  const fill = (raw, attr) => raw.replace(
    new RegExp(`(<(\\w+)\\b[^>]*\\b${attr}="([^"]+)"[^>]*>)\\s*(</\\2>)`, "g"),
    (m, open, _tag, key, close) => {
      const val = dict[key];
      if (val == null) return m;
      filled++;
      return open + (attr === "data-i18n" ? escHTML(val) : val) + close;
    }
  );
  let out = fill(html, "data-i18n");
  out = fill(out, "data-i18n-html");
  return { html: out, filled };
}

/* ── Crawlable internal links (footer only) ────────────────────────────────
   i18n.js builds the header and footer in JS, so both ship as empty shells and
   the static HTML has no internal links or anchor text for a crawler to follow.
   We emit a real link list — but into the FOOTER only, never #site-header.

   Why not the header: .site-header is position:sticky/top:0/z-index:1000, and
   nothing in the CSS styles a bare <nav>/<a> inside it (only .nav-links a). A
   pre-rendered list there paints as an unstyled band pinned to the top of the
   viewport until i18n.js swaps in the real header — a visible flash on every
   single page load. The footer is below the fold and .site-footer a is already
   styled, so the same links cost nothing visually.

   i18n.js replaces the footer on load, so this is the same content rendered
   twice, not hidden text. Labels come from i18n.js's own CORE.en dictionary so
   they cannot drift out of sync with the real navigation. */
function coreEn(src) {
  const c = src.indexOf("var CORE = {");
  if (c < 0) return null;
  const e = src.indexOf("en: {", c);
  if (e < 0) return null;
  const start = src.indexOf("{", e + 4);
  let depth = 0, i = start;
  for (; i < src.length; i++) {
    if (src[i] === "{") depth++;
    else if (src[i] === "}" && --depth === 0) break;
  }
  try { return new Function("return " + src.slice(start, i + 1))(); } catch { return null; }
}

const NAV = [
  ["index.html", "nav.home"], ["map.html", "nav.map"], ["insights.html", "nav.insights"],
  ["preparedness.html", "nav.prep"], ["plan.html", "nav.plan"], ["felt.html", "nav.felt"],
  ["building.html", "nav.building"], ["district.html", "nav.district"],
  ["aftermath.html", "nav.after"], ["facts.html", "nav.facts"], ["faq.html", "nav.faq"],
  ["resources.html", "nav.resources"], ["directory.html", "nav.directory"],
  ["alerts.html", "nav.alerts"], ["about.html", "nav.about"]
];

const core = coreEn(await readFile(path.join(DIST, "assets", "js", "i18n.js"), "utf8"));
let footHTML = "";
if (core && core["nav.home"]) {
  const links = NAV.filter(([, k]) => core[k])
    .map(([href, k]) => `<a href="${href}">${escHTML(core[k])}</a>`).join("\n      ");
  const p = (k) => (core[k] ? `<p>${escHTML(core[k])}</p>\n    ` : "");
  footHTML = `\n    ${p("foot.tagline")}<nav aria-label="Site">\n      ${links}\n    </nav>\n    ` +
    `${p("foot.police")}${p("foot.disclaimer")}`;
} else {
  console.warn("build: could not read CORE.en — skipping footer pre-render");
}

// Footer only — see the note above on why #site-header is left alone.
function injectShell(html) {
  let n = 0;
  if (footHTML) {
    html = html.replace(/(<footer[^>]*id="site-footer"[^>]*>)\s*(<\/footer>)/i,
      (m, a, b) => { n++; return a + footHTML + b; });
  }
  return { html, n };
}

let prerendered = 0, prerenderedPages = 0, shells = 0;
for (const file of await walk(DIST)) {
  if (!file.endsWith(".html")) continue;
  const src = await readFile(file, "utf8");
  const step1 = prerenderI18n(src);
  const step2 = injectShell(step1.html);
  if (!step1.filled && !step2.n) continue;
  await writeFile(file, step2.html);
  prerendered += step1.filled; shells += step2.n;
  if (step1.filled) prerenderedPages++;
}
console.log(`Pre-rendered ${prerendered} i18n strings across ${prerenderedPages} pages; filled ${shells} nav/footer shells`);

/* ── Sitemap freshness ─────────────────────────────────────────────────────
   The sitemap ships <changefreq> and <priority> — both of which Google states
   it ignores — and no <lastmod> at all, so it carries no signal that anything
   ever changed. Stamp each URL with its file's last commit date so a recrawl
   can be prioritised. If git isn't available we omit lastmod rather than
   invent a date: a wrong freshness claim is worse than none. */
try {
  const smPath = path.join(DIST, "sitemap.xml");
  let sm = await readFile(smPath, "utf8");
  const gitDate = (file) => {
    try {
      return execFileSync("git", ["log", "-1", "--format=%cI", "--", file],
        { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim() || null;
    } catch { return null; }
  };
  let stamped = 0;
  sm = sm.replace(/<loc>([^<]+)<\/loc>(?!\s*<lastmod>)/g, (m, loc) => {
    const rel = loc.replace(/^https?:\/\/[^/]+\/?/, "") || "index.html";
    const d = gitDate(rel);
    if (!d) return m;
    stamped++;
    return `${m}<lastmod>${d.slice(0, 10)}</lastmod>`;
  });
  if (stamped) {
    await writeFile(smPath, sm);
    console.log(`Sitemap: stamped ${stamped} <lastmod> dates`);
  } else {
    console.warn("Sitemap: no <lastmod> stamped (git unavailable?)");
  }
} catch { /* the sitemap is optional — never fail a build over it */ }

let css = 0, js = 0, before = 0, after = 0;
for (const file of await walk(DIST)) {
  if (file.endsWith(".css")) {
    const src = await readFile(file, "utf8");
    const r = new CleanCSS({ level: 1 }).minify(src);   // level 1 = safe (no aggressive restructuring)
    if (r.errors.length) throw new Error(file + ": " + r.errors.join("; "));
    before += src.length; after += r.styles.length; css++;
    await writeFile(file, r.styles);
  } else if (file.endsWith(".js")) {
    const src = await readFile(file, "utf8");
    // VERSION is intentionally stable so the artifact smoke test can verify
    // that the minified footer and service-worker versions remain in sync.
    const r = await terser(src, { compress: true, mangle: { reserved: ["VERSION"] } });
    if (!r.code) throw new Error(file + ": terser produced no output");
    before += src.length; after += r.code.length; js++;
    await writeFile(file, r.code);
  }
}

console.log(`Minified ${css} CSS + ${js} JS files into dist/`);
console.log(`Asset bytes: ${kb(before)} -> ${kb(after)} (then gzip/brotli at serve time).`);
console.log("Deploy the dist/ folder.");
