/* ==========================================================================
   EQ Sentry — production build.
   Copies the whole site into dist/ and minifies the CSS + JS there, leaving the
   source files readable. Deploy the dist/ folder.

     npm install      # one time (clean-css + terser)
     npm run build    # produces ./dist
     # then deploy ./dist  (it already contains _headers, manifest, data, etc.)

   Requires Node 18+. clean-css/terser are correct minifiers — they preserve
   calc() spacing, strings, and only mangle local variables (not window.EQ etc.),
   so this is safe in a way a hand-rolled regex minifier is not.

   Note: most hosts (Netlify, Cloudflare, Vercel) already gzip/brotli responses,
   which delivers ~70–75% of this size win automatically. This build adds the
   rest and is worth wiring into CI.
   ========================================================================== */
import { cp, mkdir, rm, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import CleanCSS from "clean-css";
import { minify as terser } from "terser";

const ROOT = process.cwd();
const DIST = path.join(ROOT, "dist");

// Explicit allowlist: local backups, logs, dotfiles, .env files, tooling and
// other untracked workspace content must never leak into a deployed bundle.
const SITE_DIRS = new Set(["assets", "data"]);
const SITE_FILES = new Set([
  "_headers", "_redirects", ".nojekyll", "CNAME",
  "manifest.webmanifest", "netlify.toml", "robots.txt", "service-worker.js", "sitemap.xml"
]);

function shouldShip(entry) {
  return entry.isDirectory()
    ? SITE_DIRS.has(entry.name)
    : entry.name.endsWith(".html") || SITE_FILES.has(entry.name);
}

async function walk(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...await walk(p));
    else out.push(p);
  }
  return out;
}

const kb = (n) => (n / 1024).toFixed(1) + " KB";

await rm(DIST, { recursive: true, force: true });
await mkdir(DIST, { recursive: true });

// fs.cp rejects copying a directory into one of its own descendants before its
// filter runs. Copy each shippable top-level entry instead so dist/ can live in
// the project root without recursively copying itself.
for (const entry of await readdir(ROOT, { withFileTypes: true })) {
  if (!shouldShip(entry)) continue;
  await cp(path.join(ROOT, entry.name), path.join(DIST, entry.name), {
    recursive: true
  });
}
await writeFile(path.join(DIST, ".eqsentry-static-root"), "generated by npm run build\n");

let css = 0, js = 0, before = 0, after = 0;
for (const file of await walk(DIST)) {
  if (file.endsWith(".css")) {
    const src = await readFile(file, "utf8");
    const r = new CleanCSS({ level: 1 }).minify(src);   // level 1 = safe (no aggressive restructuring)
    if (r.errors.length) throw new Error(file + ": " + r.errors.join("; "));
    before += src.length; after += r.styles.length; css++;
    await writeFile(file, r.styles);
  } else if (file.endsWith(".js")) {
    const src = await readFile(file, "utf8");
    // VERSION is intentionally stable so the artifact smoke test can verify
    // that the minified footer and service-worker versions remain in sync.
    const r = await terser(src, { compress: true, mangle: { reserved: ["VERSION"] } });
    if (!r.code) throw new Error(file + ": terser produced no output");
    before += src.length; after += r.code.length; js++;
    await writeFile(file, r.code);
  }
}

console.log(`Minified ${css} CSS + ${js} JS files into dist/`);
console.log(`Asset bytes: ${kb(before)} -> ${kb(after)} (then gzip/brotli at serve time).`);
console.log("Deploy the dist/ folder.");
